version: '4.14'

services: 
    mysqldb:
        image: mysql:latest
        ports:
        - 3306:3306
        environment: 
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE= ${DB_NAME}
        volumes: 
        - mysqlVolume:/var/lib/mysql
        - mysqlConfig:/etc/mysql
        hostname: mysql
    

volumes: 
    mysqlVolume:
    mysqlConfig: