version: '3.9'

services:
  mysqldb:
    image: mysql:latest
    ports:
      - 3306:3306
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASS}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - mysqlVolume:/var/lib/mysql
      - mysqlConfig:/etc/mysql
    hostname: mysqldb
    networks:
      - mynetwork

  fastapi-app:
    image: fastapi-app-crypto
    ports:
      - 8000:8000
    depends_on:
      - mysqldb
    networks:
      - mynetwork

volumes:
  mysqlVolume:
  mysqlConfig:

networks:
  mynetwork:
